apiVersion: apps/v1
kind: Deployment
metadata:
  name: ise-prod-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ise-prod-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ise-prod-api
    spec:
      containers:
      - image: gcr.io/ise-test-404109/ise-prod-api:latest
        name: ise-prod-api
        imagePullPolicy: Always
        ports:
          - containerPort: 3006
        envFrom:
          - secretRef:
              name: prod-api-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ise-prod-api
  name: ise-prod-api
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3006
  selector:
    app: ise-prod-api
